// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gldmszykmzbbsljxtnyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZG1zenlrbXpiYnNsanh0bnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1Mjg4OTAsImV4cCI6MjA3NDEwNDg5MH0._P6uGg9Jczd5VcBdxOjk8vFyIltIhuj3Cmg-miwxZrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});